[connections.my_database]
    type="sql"
    dialect="mysql"
    username="root"
    password="0000"
    host="localhost" # IP or URL
    port=5503 # Port number
    database="my_test" # Database name